name: Run Dockerized Regression Tests

on:
  push:
    branches:
      - docker-tests-integration

jobs:
  docker-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout frontend repo
        uses: actions/checkout@v4

      - name: Clone Playwright test repo (private)
        run: |
          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/AlexnderDoroshenko/taf_playwright_ts_js.git
        shell: bash

      - name: Run docker compose
        run: |
          docker compose version || docker-compose version
          (docker compose up --abort-on-container-exit --build) || (docker-compose up --abort-on-container-exit --build)

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
